// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/post.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Post struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content              string   `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	TimestampCreated     string   `protobuf:"bytes,4,opt,name=timestamp_created,json=timestampCreated,proto3" json:"timestamp_created,omitempty"`
	TimestampUpdated     string   `protobuf:"bytes,5,opt,name=timestamp_updated,json=timestampUpdated,proto3" json:"timestamp_updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Post) Reset()         { *m = Post{} }
func (m *Post) String() string { return proto.CompactTextString(m) }
func (*Post) ProtoMessage()    {}
func (*Post) Descriptor() ([]byte, []int) {
	return fileDescriptor_44e633a5eb8e0f8a, []int{0}
}

func (m *Post) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Post.Unmarshal(m, b)
}
func (m *Post) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Post.Marshal(b, m, deterministic)
}
func (m *Post) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Post.Merge(m, src)
}
func (m *Post) XXX_Size() int {
	return xxx_messageInfo_Post.Size(m)
}
func (m *Post) XXX_DiscardUnknown() {
	xxx_messageInfo_Post.DiscardUnknown(m)
}

var xxx_messageInfo_Post proto.InternalMessageInfo

func (m *Post) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Post) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Post) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *Post) GetTimestampCreated() string {
	if m != nil {
		return m.TimestampCreated
	}
	return ""
}

func (m *Post) GetTimestampUpdated() string {
	if m != nil {
		return m.TimestampUpdated
	}
	return ""
}

type CreatePostRequest struct {
	Post                 *Post    `protobuf:"bytes,1,opt,name=post,proto3" json:"post,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePostRequest) Reset()         { *m = CreatePostRequest{} }
func (m *CreatePostRequest) String() string { return proto.CompactTextString(m) }
func (*CreatePostRequest) ProtoMessage()    {}
func (*CreatePostRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_44e633a5eb8e0f8a, []int{1}
}

func (m *CreatePostRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePostRequest.Unmarshal(m, b)
}
func (m *CreatePostRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePostRequest.Marshal(b, m, deterministic)
}
func (m *CreatePostRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePostRequest.Merge(m, src)
}
func (m *CreatePostRequest) XXX_Size() int {
	return xxx_messageInfo_CreatePostRequest.Size(m)
}
func (m *CreatePostRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePostRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePostRequest proto.InternalMessageInfo

func (m *CreatePostRequest) GetPost() *Post {
	if m != nil {
		return m.Post
	}
	return nil
}

type CreatePostResponse struct {
	Post                 *Post    `protobuf:"bytes,1,opt,name=post,proto3" json:"post,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePostResponse) Reset()         { *m = CreatePostResponse{} }
func (m *CreatePostResponse) String() string { return proto.CompactTextString(m) }
func (*CreatePostResponse) ProtoMessage()    {}
func (*CreatePostResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_44e633a5eb8e0f8a, []int{2}
}

func (m *CreatePostResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePostResponse.Unmarshal(m, b)
}
func (m *CreatePostResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePostResponse.Marshal(b, m, deterministic)
}
func (m *CreatePostResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePostResponse.Merge(m, src)
}
func (m *CreatePostResponse) XXX_Size() int {
	return xxx_messageInfo_CreatePostResponse.Size(m)
}
func (m *CreatePostResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePostResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePostResponse proto.InternalMessageInfo

func (m *CreatePostResponse) GetPost() *Post {
	if m != nil {
		return m.Post
	}
	return nil
}

type ReadPostRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadPostRequest) Reset()         { *m = ReadPostRequest{} }
func (m *ReadPostRequest) String() string { return proto.CompactTextString(m) }
func (*ReadPostRequest) ProtoMessage()    {}
func (*ReadPostRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_44e633a5eb8e0f8a, []int{3}
}

func (m *ReadPostRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadPostRequest.Unmarshal(m, b)
}
func (m *ReadPostRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadPostRequest.Marshal(b, m, deterministic)
}
func (m *ReadPostRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadPostRequest.Merge(m, src)
}
func (m *ReadPostRequest) XXX_Size() int {
	return xxx_messageInfo_ReadPostRequest.Size(m)
}
func (m *ReadPostRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadPostRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadPostRequest proto.InternalMessageInfo

func (m *ReadPostRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ReadPostResponse struct {
	Post                 *Post    `protobuf:"bytes,1,opt,name=post,proto3" json:"post,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadPostResponse) Reset()         { *m = ReadPostResponse{} }
func (m *ReadPostResponse) String() string { return proto.CompactTextString(m) }
func (*ReadPostResponse) ProtoMessage()    {}
func (*ReadPostResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_44e633a5eb8e0f8a, []int{4}
}

func (m *ReadPostResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadPostResponse.Unmarshal(m, b)
}
func (m *ReadPostResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadPostResponse.Marshal(b, m, deterministic)
}
func (m *ReadPostResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadPostResponse.Merge(m, src)
}
func (m *ReadPostResponse) XXX_Size() int {
	return xxx_messageInfo_ReadPostResponse.Size(m)
}
func (m *ReadPostResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadPostResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadPostResponse proto.InternalMessageInfo

func (m *ReadPostResponse) GetPost() *Post {
	if m != nil {
		return m.Post
	}
	return nil
}

type UpdatePostRequest struct {
	Post                 *Post    `protobuf:"bytes,1,opt,name=post,proto3" json:"post,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdatePostRequest) Reset()         { *m = UpdatePostRequest{} }
func (m *UpdatePostRequest) String() string { return proto.CompactTextString(m) }
func (*UpdatePostRequest) ProtoMessage()    {}
func (*UpdatePostRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_44e633a5eb8e0f8a, []int{5}
}

func (m *UpdatePostRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePostRequest.Unmarshal(m, b)
}
func (m *UpdatePostRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePostRequest.Marshal(b, m, deterministic)
}
func (m *UpdatePostRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePostRequest.Merge(m, src)
}
func (m *UpdatePostRequest) XXX_Size() int {
	return xxx_messageInfo_UpdatePostRequest.Size(m)
}
func (m *UpdatePostRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePostRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePostRequest proto.InternalMessageInfo

func (m *UpdatePostRequest) GetPost() *Post {
	if m != nil {
		return m.Post
	}
	return nil
}

type UpdatePostResponse struct {
	Post                 *Post    `protobuf:"bytes,1,opt,name=post,proto3" json:"post,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdatePostResponse) Reset()         { *m = UpdatePostResponse{} }
func (m *UpdatePostResponse) String() string { return proto.CompactTextString(m) }
func (*UpdatePostResponse) ProtoMessage()    {}
func (*UpdatePostResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_44e633a5eb8e0f8a, []int{6}
}

func (m *UpdatePostResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePostResponse.Unmarshal(m, b)
}
func (m *UpdatePostResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePostResponse.Marshal(b, m, deterministic)
}
func (m *UpdatePostResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePostResponse.Merge(m, src)
}
func (m *UpdatePostResponse) XXX_Size() int {
	return xxx_messageInfo_UpdatePostResponse.Size(m)
}
func (m *UpdatePostResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePostResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePostResponse proto.InternalMessageInfo

func (m *UpdatePostResponse) GetPost() *Post {
	if m != nil {
		return m.Post
	}
	return nil
}

type DeletePostRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeletePostRequest) Reset()         { *m = DeletePostRequest{} }
func (m *DeletePostRequest) String() string { return proto.CompactTextString(m) }
func (*DeletePostRequest) ProtoMessage()    {}
func (*DeletePostRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_44e633a5eb8e0f8a, []int{7}
}

func (m *DeletePostRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeletePostRequest.Unmarshal(m, b)
}
func (m *DeletePostRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeletePostRequest.Marshal(b, m, deterministic)
}
func (m *DeletePostRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeletePostRequest.Merge(m, src)
}
func (m *DeletePostRequest) XXX_Size() int {
	return xxx_messageInfo_DeletePostRequest.Size(m)
}
func (m *DeletePostRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeletePostRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeletePostRequest proto.InternalMessageInfo

func (m *DeletePostRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeletePostResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeletePostResponse) Reset()         { *m = DeletePostResponse{} }
func (m *DeletePostResponse) String() string { return proto.CompactTextString(m) }
func (*DeletePostResponse) ProtoMessage()    {}
func (*DeletePostResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_44e633a5eb8e0f8a, []int{8}
}

func (m *DeletePostResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeletePostResponse.Unmarshal(m, b)
}
func (m *DeletePostResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeletePostResponse.Marshal(b, m, deterministic)
}
func (m *DeletePostResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeletePostResponse.Merge(m, src)
}
func (m *DeletePostResponse) XXX_Size() int {
	return xxx_messageInfo_DeletePostResponse.Size(m)
}
func (m *DeletePostResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeletePostResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeletePostResponse proto.InternalMessageInfo

func (m *DeletePostResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func init() {
	proto.RegisterType((*Post)(nil), "pb.Post")
	proto.RegisterType((*CreatePostRequest)(nil), "pb.CreatePostRequest")
	proto.RegisterType((*CreatePostResponse)(nil), "pb.CreatePostResponse")
	proto.RegisterType((*ReadPostRequest)(nil), "pb.ReadPostRequest")
	proto.RegisterType((*ReadPostResponse)(nil), "pb.ReadPostResponse")
	proto.RegisterType((*UpdatePostRequest)(nil), "pb.UpdatePostRequest")
	proto.RegisterType((*UpdatePostResponse)(nil), "pb.UpdatePostResponse")
	proto.RegisterType((*DeletePostRequest)(nil), "pb.DeletePostRequest")
	proto.RegisterType((*DeletePostResponse)(nil), "pb.DeletePostResponse")
}

func init() { proto.RegisterFile("pb/post.proto", fileDescriptor_44e633a5eb8e0f8a) }

var fileDescriptor_44e633a5eb8e0f8a = []byte{
	// 331 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0xbd, 0x4e, 0xf3, 0x40,
	0x10, 0x4c, 0xfc, 0x25, 0x5f, 0xc2, 0x46, 0x40, 0xbc, 0x04, 0x74, 0x8a, 0x28, 0xe0, 0x68, 0x90,
	0x90, 0x0c, 0x31, 0x05, 0x55, 0x2a, 0x78, 0x00, 0x64, 0x44, 0x8d, 0xfc, 0xb3, 0x85, 0xa5, 0xc4,
	0x77, 0xf8, 0xce, 0xbc, 0x00, 0x2f, 0xc2, 0xa3, 0x22, 0xdf, 0xe1, 0xf8, 0xaf, 0x20, 0x94, 0x3b,
	0x37, 0xb3, 0x33, 0x3b, 0x96, 0xe1, 0x50, 0x46, 0xb7, 0x52, 0x28, 0xed, 0xc9, 0x5c, 0x68, 0x81,
	0x8e, 0x8c, 0xf8, 0xd7, 0x10, 0x46, 0xcf, 0x42, 0x69, 0x3c, 0x02, 0x27, 0x4d, 0xd8, 0xf0, 0x62,
	0x78, 0x7d, 0x10, 0x38, 0x69, 0x82, 0x0b, 0x18, 0xeb, 0x54, 0x6f, 0x88, 0x39, 0x06, 0xb2, 0x03,
	0x32, 0x98, 0xc4, 0x22, 0xd3, 0x94, 0x69, 0xf6, 0xcf, 0xe0, 0xd5, 0x88, 0x37, 0xe0, 0xea, 0x74,
	0x4b, 0x4a, 0x87, 0x5b, 0xf9, 0x16, 0xe7, 0x14, 0x6a, 0x4a, 0xd8, 0xc8, 0x70, 0xe6, 0xbb, 0x87,
	0x47, 0x8b, 0xb7, 0xc9, 0x85, 0x4c, 0x0c, 0x79, 0xdc, 0x21, 0xbf, 0x5a, 0x9c, 0xaf, 0xc0, 0xb5,
	0xba, 0x32, 0x67, 0x40, 0xef, 0x05, 0x29, 0x8d, 0xe7, 0x30, 0x2a, 0x2f, 0x31, 0x81, 0x67, 0xfe,
	0xd4, 0x93, 0x91, 0x67, 0x9e, 0x0d, 0xca, 0x7d, 0xc0, 0xa6, 0x44, 0x49, 0x91, 0x29, 0xfa, 0x45,
	0x73, 0x09, 0xc7, 0x01, 0x85, 0x49, 0xd3, 0xa4, 0xd3, 0x09, 0xbf, 0x83, 0x79, 0x4d, 0xd9, 0x6b,
	0xe9, 0x0a, 0x5c, 0x7b, 0xc6, 0x9f, 0xb2, 0x37, 0x25, 0x7b, 0xd9, 0x5c, 0x81, 0xfb, 0x44, 0x1b,
	0x6a, 0xdb, 0x74, 0xd3, 0x7b, 0x80, 0x4d, 0xd2, 0xcf, 0x62, 0x06, 0x13, 0x55, 0xc4, 0x31, 0x29,
	0x65, 0xa8, 0xd3, 0xa0, 0x1a, 0xfd, 0x4f, 0x07, 0x66, 0x25, 0xf5, 0x85, 0xf2, 0x8f, 0x34, 0x26,
	0x5c, 0x03, 0xd4, 0xa5, 0xe2, 0x69, 0x19, 0xa1, 0xf7, 0x5d, 0x96, 0x67, 0x5d, 0xd8, 0xda, 0xf0,
	0x01, 0x3e, 0xc0, 0xb4, 0x2a, 0x0f, 0x4f, 0x4a, 0x56, 0xa7, 0xed, 0xe5, 0xa2, 0x0d, 0xee, 0x84,
	0x6b, 0x80, 0xba, 0x10, 0xeb, 0xdb, 0xeb, 0xd4, 0xfa, 0xf6, 0x7b, 0xb3, 0xf2, 0xfa, 0x6c, 0x2b,
	0xef, 0x75, 0x65, 0xe5, 0xfd, 0x76, 0xf8, 0x20, 0xfa, 0x6f, 0xfe, 0x95, 0xfb, 0xef, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x46, 0x5b, 0x4a, 0x16, 0x3c, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PostServiceClient is the client API for PostService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PostServiceClient interface {
	CreatePost(ctx context.Context, in *CreatePostRequest, opts ...grpc.CallOption) (*CreatePostResponse, error)
	ReadPost(ctx context.Context, in *ReadPostRequest, opts ...grpc.CallOption) (*ReadPostResponse, error)
	UpdatePost(ctx context.Context, in *UpdatePostRequest, opts ...grpc.CallOption) (*UpdatePostResponse, error)
	DeletePost(ctx context.Context, in *DeletePostRequest, opts ...grpc.CallOption) (*DeletePostResponse, error)
}

type postServiceClient struct {
	cc *grpc.ClientConn
}

func NewPostServiceClient(cc *grpc.ClientConn) PostServiceClient {
	return &postServiceClient{cc}
}

func (c *postServiceClient) CreatePost(ctx context.Context, in *CreatePostRequest, opts ...grpc.CallOption) (*CreatePostResponse, error) {
	out := new(CreatePostResponse)
	err := c.cc.Invoke(ctx, "/pb.PostService/CreatePost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postServiceClient) ReadPost(ctx context.Context, in *ReadPostRequest, opts ...grpc.CallOption) (*ReadPostResponse, error) {
	out := new(ReadPostResponse)
	err := c.cc.Invoke(ctx, "/pb.PostService/ReadPost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postServiceClient) UpdatePost(ctx context.Context, in *UpdatePostRequest, opts ...grpc.CallOption) (*UpdatePostResponse, error) {
	out := new(UpdatePostResponse)
	err := c.cc.Invoke(ctx, "/pb.PostService/UpdatePost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postServiceClient) DeletePost(ctx context.Context, in *DeletePostRequest, opts ...grpc.CallOption) (*DeletePostResponse, error) {
	out := new(DeletePostResponse)
	err := c.cc.Invoke(ctx, "/pb.PostService/DeletePost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PostServiceServer is the server API for PostService service.
type PostServiceServer interface {
	CreatePost(context.Context, *CreatePostRequest) (*CreatePostResponse, error)
	ReadPost(context.Context, *ReadPostRequest) (*ReadPostResponse, error)
	UpdatePost(context.Context, *UpdatePostRequest) (*UpdatePostResponse, error)
	DeletePost(context.Context, *DeletePostRequest) (*DeletePostResponse, error)
}

// UnimplementedPostServiceServer can be embedded to have forward compatible implementations.
type UnimplementedPostServiceServer struct {
}

func (*UnimplementedPostServiceServer) CreatePost(ctx context.Context, req *CreatePostRequest) (*CreatePostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePost not implemented")
}
func (*UnimplementedPostServiceServer) ReadPost(ctx context.Context, req *ReadPostRequest) (*ReadPostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadPost not implemented")
}
func (*UnimplementedPostServiceServer) UpdatePost(ctx context.Context, req *UpdatePostRequest) (*UpdatePostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePost not implemented")
}
func (*UnimplementedPostServiceServer) DeletePost(ctx context.Context, req *DeletePostRequest) (*DeletePostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeletePost not implemented")
}

func RegisterPostServiceServer(s *grpc.Server, srv PostServiceServer) {
	s.RegisterService(&_PostService_serviceDesc, srv)
}

func _PostService_CreatePost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServiceServer).CreatePost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.PostService/CreatePost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServiceServer).CreatePost(ctx, req.(*CreatePostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostService_ReadPost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadPostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServiceServer).ReadPost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.PostService/ReadPost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServiceServer).ReadPost(ctx, req.(*ReadPostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostService_UpdatePost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServiceServer).UpdatePost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.PostService/UpdatePost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServiceServer).UpdatePost(ctx, req.(*UpdatePostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostService_DeletePost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServiceServer).DeletePost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.PostService/DeletePost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServiceServer).DeletePost(ctx, req.(*DeletePostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PostService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.PostService",
	HandlerType: (*PostServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePost",
			Handler:    _PostService_CreatePost_Handler,
		},
		{
			MethodName: "ReadPost",
			Handler:    _PostService_ReadPost_Handler,
		},
		{
			MethodName: "UpdatePost",
			Handler:    _PostService_UpdatePost_Handler,
		},
		{
			MethodName: "DeletePost",
			Handler:    _PostService_DeletePost_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/post.proto",
}
